"""initial migration

Revision ID: 1d76212c158d
Revises: None
Create Date: 2016-08-17 22:49:57.986000

"""

# revision identifiers, used by Alembic.
revision = '1d76212c158d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_roles_dafault'), 'roles', ['dafault'], unique=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_dafault'), table_name='roles')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    ### end Alembic commands ###
